# $NetBSD$

DISTNAME=	openresty-1.13.6.2
CATEGORIES=	www
MASTER_SITES=	https://openresty.org/download/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE
HOMEPAGE=	https://openresty.org/download/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

HAS_CONFIGURE=	yes
CONFIG_SHELL= perl
USE_LANGUAGES=	c c++

.include "../../mk/bsd.pkg.mk"
.include "../../devel/zlib/buildlink3.mk"
