# $NetBSD$

DISTNAME=	openresty-1.13.6.2
CATEGORIES=	www
MASTER_SITES=	https://openresty.org/download/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE
HOMEPAGE=	https://openresty.org/download/
COMMENT=	Scalable Web Platform by Extending NGINX with Lua
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
.include "../../devel/zlib/buildlink3.mk"
