# $NetBSD$

DISTNAME=	openresty-1.13.6.2
CATEGORIES=	www
MASTER_SITES=	https://openresty.org/download/

MAINTAINER=	pkgsrc@philipcristiano.com	
HOMEPAGE=	https://openresty.org/download/
COMMENT=	Scalable Web Platform by Extending NGINX with Lua
#LICENSE=	# TODO: (see mk/license.mk)

HAS_CONFIGURE=	yes
USE_LANGUAGES=	c c++

.include "../../devel/zlib/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"

